/*
| regdNo | varchar(20) | NO   | PRI | NULL    |       |
| G111   | varchar(2)  | YES  |     | NULL    |       |
| G112   | varchar(2)  | YES  |     | NULL    |       |
| G113   | varchar(2)  | YES  |     | NULL    |       |
| G114   | varchar(2)  | YES  |     | NULL    |       |
| G115   | varchar(2)  | YES  |     | NULL    |       |
| G116   | varchar(2)  | YES  |     | NULL    |       |
| G117   | varchar(2)  | YES  |     | NULL    |       |
| G118   | varchar(2)  | YES  |     | NULL    |       |
| G119   | varchar(2)  | YES  |     | NULL    |       |
| G121   | varchar(2)  | YES  |     | NULL    |       |
| G122   | varchar(2)  | YES  |     | NULL    |       |
| G123   | varchar(2)  | YES  |     | NULL    |       |
| G124   | varchar(2)  | YES  |     | NULL    |       |
| G125   | varchar(2)  | YES  |     | NULL    |       |
| G126   | varchar(2)  | YES  |     | NULL    |       |
| G127   | varchar(2)  | YES  |     | NULL    |       |
| G128   | varchar(2)  | YES  |     | NULL    |       |
| G129   | varchar(2)  | YES  |     | NULL    |       |
| G211   | varchar(2)  | YES  |     | NULL    |       |
| G212   | varchar(2)  | YES  |     | NULL    |       |
| G213   | varchar(2)  | YES  |     | NULL    |       |
| G214   | varchar(2)  | YES  |     | NULL    |       |
| G215   | varchar(2)  | YES  |     | NULL    |       |
| G216   | varchar(2)  | YES  |     | NULL    |       |
| G217   | varchar(2)  | YES  |     | NULL    |       |
| G218   | varchar(2)  | YES  |     | NULL    |       |
| G219   | varchar(2)  | YES  |     | NULL    |       |
| G221   | varchar(2)  | YES  |     | NULL    |       |
| G222   | varchar(2)  | YES  |     | NULL    |       |
| G223   | varchar(2)  | YES  |     | NULL    |       |
| G224   | varchar(2)  | YES  |     | NULL    |       |
| G225   | varchar(2)  | YES  |     | NULL    |       |
| G226   | varchar(2)  | YES  |     | NULL    |       |
| G227   | varchar(2)  | YES  |     | NULL    |       |
| G228   | varchar(2)  | YES  |     | NULL    |       |
| G229   | varchar(2)  | YES  |     | NULL    |       |
| G311   | varchar(2)  | YES  |     | NULL    |       |
| G312   | varchar(2)  | YES  |     | NULL    |       |
| G313   | varchar(2)  | YES  |     | NULL    |       |
| G314   | varchar(2)  | YES  |     | NULL    |       |
| G315   | varchar(2)  | YES  |     | NULL    |       |
| G316   | varchar(2)  | YES  |     | NULL    |       |
| G317   | varchar(2)  | YES  |     | NULL    |       |
| G318   | varchar(2)  | YES  |     | NULL    |       |
| G319   | varchar(2)  | YES  |     | NULL    |       |
| G321   | varchar(2)  | YES  |     | NULL    |       |
| G322   | varchar(2)  | YES  |     | NULL    |       |
| G323   | varchar(2)  | YES  |     | NULL    |       |
| G324   | varchar(2)  | YES  |     | NULL    |       |
| G325   | varchar(2)  | YES  |     | NULL    |       |
| G326   | varchar(2)  | YES  |     | NULL    |       |
| G327   | varchar(2)  | YES  |     | NULL    |       |
| G328   | varchar(2)  | YES  |     | NULL    |       |
| G329   | varchar(2)  | YES  |     | NULL    |       |
| G411   | varchar(2)  | YES  |     | NULL    |       |
| G412   | varchar(2)  | YES  |     | NULL    |       |
| G413   | varchar(2)  | YES  |     | NULL    |       |
| G414   | varchar(2)  | YES  |     | NULL    |       |
| G415   | varchar(2)  | YES  |     | NULL    |       |
| G416   | varchar(2)  | YES  |     | NULL    |       |
| G417   | varchar(2)  | YES  |     | NULL    |       |
| G418   | varchar(2)  | YES  |     | NULL    |       |
| G419   | varchar(2)  | YES  |     | NULL    |       |
| G421   | varchar(2)  | YES  |     | NULL    |       |
| G422   | varchar(2)  | YES  |     | NULL    |       |
| G423   | varchar(2)  | YES  |     | NULL    |       |
| G424   | varchar(2)  | YES  |     | NULL    |       |
| G425   | varchar(2)  | YES  |     | NULL    |       |
| G426   | varchar(2)  | YES  |     | NULL    |       |
| G427   | varchar(2)  | YES  |     | NULL    |       |
| G428   | varchar(2)  | YES  |     | NULL    |       |
| G429   | varchar(2)  | YES  |     | NULL    |       |
*/